pip's CLI completion code no longer prints a Traceback if it is interrupted.
